redis:
  host: 127.0.0.1:6379
  password: ""

mysql:
  dsn: root:@tcp(127.0.0.1:3306)/gin_api?charset=utf8mb4&parseTime=True&loc=Local
  prefix: gin_

app:
  read_time_out: 2
  write_time_out: 2
  run_mode: debug #release(gin.ReleaseMode ) test(gin.TestMode) debug(gin.DebugMode )
  http_port: 8999